#!/bin/bash

source $SCRIPTS_DIR/colors	#nastavi barvy
source $SCRIPTS_DIR/prepare	#nastavi promene a kontroluje existenci dulezitych slozek

echo -e "$C spousti se chroot do systemu $DEF"
chroot "$LFS" /tools/bin/env -i HOME=/root TERM="$TERM" PS1='\u:\w\$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin SCRIPTS_DIR=/scripts /tools/bin/bash --login +h