#!/bin/bash

BUILD_RM=1 #URCUJE ZDA SE MA SMAZAT SLOZKA S BUIDEM 1=ANO
BUILD_TEST=1 #1=tests

ROOT=/
#LC_ALL=POSIX
#LFS_TGT=$(uname -m)-lfs-linux-gnu
#PATH=/tools/bin:/bin:/usr/bin
#export LFS LC_ALL LFS_TGT PATH

export SOURCES_DIR=/sources
export BUILD_DIR=/build
export TOOLS_DIR=/tools
export SCRIPTS_DIR=/scripts

dprom=/bin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/boot
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi

dprom=/etc
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi

dprom=/etc/opt
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/home
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/lib
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/mnt
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/opt
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/media
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/media/floppy
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/media/cdrom
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/sbin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/srv
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/var
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/bin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi

dprom=/bin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
install -dv -m 0750 /root
install -dv -m 1777 /tmp /var/tmp

dprom=/usr
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/bin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/include
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/lib
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/sbin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/src
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/bin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/include
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/lib
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/sbin
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/src
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/share/doc
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/share/info
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/share/locale
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/share/man
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/share/doc
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/share/info
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/share/locale
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/local/share/man
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/usr/share/misc
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/terminfo
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/zoneinfo
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/misc
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/terminfo
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/zoneinfo
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man1
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man2
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man3
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man4
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man5
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man6
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man7
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/share/man/man8
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man1
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man2
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man3
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man4
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man5
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man6
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man7
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/usr/local/share/man/man8
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi

for dir in /usr /usr/local; do
ln -sv share/{man,doc,info} $dir
done

dprom=/var/lock
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/var/log
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/var/mail
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/var/run
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/var/spool
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -v $dprom
fi
dprom=/var/opt
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/var/cache
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/var/lib
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/var/lib/misc
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/var/lib/locate
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi
dprom=/var/local
if [ -d $dprom ];
	then
		echo -e "$C Slozka $dprom existuje $DEF"
	else
		echo -e "$C Slozka $dprom neexistuje $DEF"
		echo -e "$G mkdir -pv $dprom $DEF"
		mkdir -pv $dprom
fi

if [ -L /bin/bash ];
	then
		echo -e "$C Symbolicky odkaz /bin/bash existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/bash $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/bash $DEF"
		ln -sv /tools/bin/bash /bin/
fi

if [ -L /bin/cat ];
	then
		echo -e "$C Symbolicky odkaz /bin/cat existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/cat $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/cat $DEF"
		ln -sv /tools/bin/cat /bin/
fi

if [ -L /bin/echo ];
	then
		echo -e "$C Symbolicky odkaz /bin/echo existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/echo $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/echo $DEF"
		ln -sv /tools/bin/echo /bin/
fi

if [ -L /bin/echo ];
	then
		echo -e "$C Symbolicky odkaz /bin/pwd existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/pwd $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/pwd $DEF"
		ln -sv /tools/bin/pwd /bin/
fi

if [ -L /bin/stty ];
	then
		echo -e "$C Symbolicky odkaz /bin/pwd existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/pwd $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/pwd $DEF"
		ln -sv /tools/bin/stty /bin/
fi

if [ -L /bin/perl ];
	then
		echo -e "$C Symbolicky odkaz /bin/perl existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/perl $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/perl $DEF"
		ln -sv /tools/bin/perl /bin/
fi

if [ -L /lib/libgcc_s.so ];
	then
		echo -e "$C Symbolicky odkaz /lib/libgcc_s.so existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /lib/libgcc_s.so $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /lib/libgcc_s.so $DEF"
		ln -sv /tools/lib/libgcc_s.so /lib/
fi

if [ -L /lib/libgcc_s.so.1 ];
	then
		echo -e "$C Symbolicky odkaz /lib/libgcc_s.so.1 existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /lib/libgcc_s.so.1 $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /lib/libgcc_s.so.1 $DEF"
		ln -sv /tools/lib/libgcc_s.so.1 /lib/
fi

if [ -L /lib/libstdc++.so ];
	then
		echo -e "$C Symbolicky odkaz /lib/libstdc++.so existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /lib/libstdc++.so $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /lib/libstdc++.so $DEF"
		ln -sv /tools/lib/libstdc++.so /lib/
fi

if [ -L /lib/libstdc++.so.6 ];
	then
		echo -e "$C Symbolicky odkaz /lib/libstdc++.so.6 existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /lib/libstdc++.so.6 $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /lib/libstdc++.so.6 $DEF"
		ln -sv /tools/lib/libstdc++.so.6 /lib/
fi

if [ -L /bin/sh ];
	then
		echo -e "$C Symbolicky odkaz /bin/sh existuje $DEF"
	else
		echo -e "$C Symbolicky odkaz $G /bin/sh $C nexistuje nebo není symbolickým odkazem $DEF"
		echo -e "$C Vytvarim symbolicky odkaz $G /bin/sh $DEF"
		ln -sv /bin/bash /bin/sh
fi

echo -e "$C Vytvarim mtab $DEF"
echo -e "$G touch /etc/mtab $DEF"
touch /etc/mtab

echo -e "$C Vytvarim /etc/passwd $DEF"
cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

echo -e "$C Vytvarim /etc/group podle LSB $DEF"
cat > /etc/group << "EOF"
root:x:0:
bin:x:1:
sys:x:2:
kmem:x:3:
tty:x:4:
tape:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
mail:x:34:
nogroup:x:99:
EOF

echo -e "$C Vytvarim log soubory $G utmp btmp lastlog wtmp $DEF"
echo -e "$G touch /var/run/utmp /var/log/{btmp,lastlog,wtmp} $DEF"
touch /var/run/utmp /var/log/{btmp,lastlog,wtmp}
echo -e "$C Menim skupinu u $G utmp lastlog $DEF"
echo -e "$G chgrp -v utmp /var/run/utmp /var/log/lastlog  $DEF"
chgrp -v utmp /var/run/utmp /var/log/lastlog
echo -e "$C Menim prava u $G utmp lastlog $DEF"
echo -e "$G chmod -v 664 /var/run/utmp /var/log/lastlog $DEF"
chmod -v 664 /var/run/utmp /var/log/lastlog

cd $ROOT
