#!/bin/bash

#definice barev
    K="\033[0;30m"    # black
    R="\033[0;31m"    # red
    G="\033[0;32m"    # green
    Y="\033[0;33m"    # yellow
    B="\033[0;34m"    # blue
    M="\033[0;35m"    # magenta
    C="\033[0;36m"    # cyan
    W="\033[0;37m"    # white
    DEF="\033[0m"     # predchozi barva
