#!/bin/bash

source $SCRIPTS_DIR/colors	#nastavi barvy
source $SCRIPTS_DIR/prepare	#nastavi promene a kontroluje existenci dulezitych slozek
source $SCRIPTS_DIR/ver #ulozi do promenych verze programu

####### Start buildu jednotlivych aplikaci (Balicku) #######
source $SCRIPTS_DIR/chap5/finish5
###### Chapter 6 #######
source $SCRIPTS_DIR/chap6/start6
#source $SCRIPTS_DIR/chap6/restart
