#!/bin/bash

export ROOT=/
export SCRIPTS_DIR=/scripts

source $SCRIPTS_DIR/include/functions
source $SCRIPTS_DIR/include/chroot_prepare
source $SCRIPTS_DIR/include/ver
source $SCRIPTS_DIR/include/l10n-EN

####### Start builds of packages #######

source $SCRIPTS_DIR/chap7/bootscripts
source $SCRIPTS_DIR/chap7/clockInputrcProfile
source $SCRIPTS_DIR/chap7/locale
source $SCRIPTS_DIR/chap7/network
source $SCRIPTS_DIR/chap8/fstab
source $SCRIPTS_DIR/chap8/kernel
source $SCRIPTS_DIR/chap8/grub
