#!/bin/bash


export TOOLS_STRIP=0 # 1=Pro malou partition smaže nepotřebné soubory a dokumenty
export WAIT=0

export ROOT=/mnt/LFS	#složka připojeného obrazu
export LFS=$ROOT
export LC_ALL=POSIX
export LFS_TGT=$(uname -m)-lfs-linux-gnu
export PATH=/tools/bin:/bin:/usr/bin
export MAKEFLAGS='-j 3' #number of procesor cores

export SOURCES_DIR=$ROOT/sources
export BUILD_DIR=$ROOT/build
export TOOLS_DIR=$ROOT/tools
export SCRIPTS_DIR=$ROOT/scripts

echo -e "$L_CH_DIR"

testExDir $SOURCES_DIR
testExDir $BUILD_DIR
testExDir $TOOLS_DIR
testExDir $SCRIPTS_DIR
testSimLink /tools $LFS/tools /
cd $ROOT
