#!/bin/bash

NAME=linux
PROGRAM=$NAME-$linux_VER
FILE=$NAME-$linux_VER$linux_PRIP

source $SCRIPTS_DIR/initialization

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM-BUILD
	echo -e "$G ../$PROGRAM/configure $DEF" 
    ../$PROGRAM/configure
    if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi
    echo -e "$G make $DEF"
    make
    if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
    echo -e "$G make-install $DEF"
    make install
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi

if [ $BUILD_RM == 1 ];
	then
                echo -e "$C Mazu slozku s buildem $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
                rm -rf $BUILD_DIR/$PROGRAM-BUILD
                echo -e "$C Mazu slozku se zdrojaky $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
                rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi
cd $ROOT
