#!/bin/bash

NAME=bash
PROGRAM=$NAME-$bash_VER
FILE=$NAME-$bash_VER$bash_PRIP

source $SCRIPTS_DIR/include/unpack_gzip

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM

	echo -e "$C Aplikuji patch $DEF"
	echo -e "$G patch -Np1 -i $SOURCES_DIR/bash-4.1-fixes-2.patch $DEF"
	patch -Np1 -i patch -Np1 -i $SOURCES_DIR/bash-4.1-fixes-2.patch

	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/tools --without-bash-malloc
	if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi

	echo -e "$G make $DEF"
	make
	if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
	
	if [ $BUILD_TEST == 1 ] || [ $BUILD_TEST == 3 ];
    	then
			echo -e "$G make tests $DEF"
			make tests
			if [ $? -ne 0 ]
				then
					echo -e "$R make selhalo $DEF"
					exit 1
			fi
	fi
	
	echo -e "$G make-install $DEF"
	make install
	if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi

	echo -e "$C Vytvarim potrebny symbolicky odkaz $DEF"
	echo -e "$G ln -vs bash /tools/bin/sh $DEF"
	ln -vs /tools/bin/bash /tools/bin/sh
	
	if [ $BUILD_RM == 1 ];
	then
		echo -e "$C Mazu slozku se zdrojaky $DEF"
        echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
        rm -rf $BUILD_DIR/$PROGRAM

	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
	fi

cd $ROOT
