#!/bin/bash

NAME=bash
PROGRAM=$NAME-$bash_VER
FILE=$NAME-$bash_VER$bash_PRIP

unpackBzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	addPatch bash-4.1-fixes-2.patch
	
	waitUser

	c_Configure --prefix=/tools --without-bash-malloc
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi

	waitUser

	c_Make
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi

	waitUser
	
	c_MakeTest tests
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKT"
			exit 1
	fi

	waitUser
	
	c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
	
	waitUser
	
	createSimLink /tools/bin/bash /tools/bin/sh
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	  

waitUser

RMsource

cd $ROOT
