#!/bin/bash

NAME=binutils
PROGRAM=$NAME-$binutils_VER
FILE=$NAME-$binutils_VER$binutils_PRIP

unpackBzipSep

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM-BUILD
echo -e "$G ../$PROGRAM/configure $DEF" 
{
CC="$LFS_TGT-gcc -B/tools/lib/" 
AR=$LFS_TGT-ar 
RANLIB=$LFS_TGT-ranlib 

    c_ConfigureSep --prefix=/tools --disable-nls --with-lib-path=/tools/lib
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
    waitUser
    c_Make
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi
    waitUser
    c_MakeInstall
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi 
    waitUser
    c_Make -C ld clean
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
    fi
    waitUser
    c_Make -C ld LIB_PATH=/usr/lib:/lib
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
    fi

    copyFiles ld/ld-new /tools/bin

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-P2.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
