#!/bin/bash

NAME=binutils
PROGRAM=$NAME-$binutils_VER
FILE=$NAME-$binutils_VER$binutils_PRIP
TIMEFORMAT="%1R = 1 SBU - $PROGRAM"

unpackBzipSep

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM-BUILD

{ time \
  {

    c_ConfigureSep --target=$LFS_TGT --prefix=/tools --disable-nls --disable-werror
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi

    waitUser

    c_Make
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi

    waitUser

    case $(uname -m) in
    x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
    esac
    
    waitUser

    c_MakeInstall
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
  }
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
