#!/bin/bash

NAME=bzip2
PROGRAM=$NAME-$bzip2_VER
FILE=$NAME-$bzip2_VER$bzip2_PRIP

unpackGzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	c_Make || exit 1

	waitUser

	c_Make PREFIX=/tools install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMsource
cd $ROOT
