#!/bin/bash

NAME=${bzip[0]}
PROGRAM=${bzip[3]}
FILE=${bzip[2]}
EXT=${bzip[4]}
DLINK=${bzip[1]}
MD5=${bzip[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make PREFIX=/tools install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMsource
cd $ROOT
