#!/bin/bash

NAME=bzip2
PROGRAM=$NAME-$bzip2_VER
FILE=$NAME-$bzip2_VER$bzip2_PRIP

unpackGzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	c_Make
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi

	waitUser

	c_Make PREFIX=/tools install
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMsource
cd $ROOT
