#!/bin/bash

NAME=coreutils
PROGRAM=$NAME-$coreutils_VER
FILE=$NAME-$coreutils_VER$coreutils_PRIP

unpackGzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	c_Configure --prefix=/tools --enable-install-program=hostname || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest RUN_EXPENSIVE_TESTS=yes check || exit 1
	
	waitUser
	c_MakeInstall || exit 1
	waitUser
	copyFiles src/su /tools/bin/su-tools
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	

waitUser
RMsource
cd $ROOT
