#!/bin/bash

NAME=gcc
PROGRAM=$NAME-$gcc_VER
FILE=$NAME-$gcc_VER$gcc_PRIP

source $SCRIPTS_DIR/include/initialization_separate_build

cd $BUILD_DIR/$PROGRAM
{
echo -e "$C Aplikuji patch $DEF"
echo -e "$G patch -Np1 -i $SOURCES_DIR/gcc-4.4.3-startfiles_fix-1.patch $DEF"
patch -Np1 -i $SOURCES_DIR/gcc-4.4.3-startfiles_fix-1.patch

cp -v gcc/Makefile.in{,.orig}
sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in

cp -v gcc/Makefile.in{,.tmp}
sed 's/^T_CFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp > gcc/Makefile.in

for file in $(find gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
do
cp -v $file{,.orig}
sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' -e 's@/usr@/tools@g' $file.orig > $file
echo '
#undef STANDARD_INCLUDE_DIR
#define STANDARD_INCLUDE_DIR 0
#define STANDARD_STARTFILE_PREFIX_1 ""
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
touch $file.orig
done

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM-BUILD
echo -e "$G ../$PROGRAM/configure $DEF" 
CC="$LFS_TGT-gcc -B/tools/lib/" AR=$LFS_TGT-ar RANLIB=$LFS_TGT-ranlib

../$PROGRAM/configure --prefix=/tools --with-local-prefix=/tools --enable-clocale=gnu --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-languages=c,c++ --disable-libstdcxx-pch --disable-multilib --disable-bootstrap --without-ppl --without-cloog
    if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi
echo -e "$G make $DEF"
    make
    if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
echo -e "$G make-install $DEF"
    make install
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi

ln -vs gcc /tools/bin/cc

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log

if [ $BUILD_RM == 1 ];
	then
                echo -e "$C Mazu slozku s buildem $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
                rm -rf $BUILD_DIR/$PROGRAM-BUILD
                echo -e "$C Mazu slozku se zdrojaky $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
                rm -rf $BUILD_DIR/$PROGRAM
                echo -e "$C Mazu slozku se zdrojaky ke gmp $DEF"
                echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
                rm -rf $BUILD_DIR/gmp
                echo -e "$C Mazu slozku se zdrojaky mpfr $DEF"
                echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
                rm -rf $BUILD_DIR/mpfr
	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi
cd $ROOT
