#!/bin/bash

NAME=mpfr
PROGRAM=$NAME-$mpfr_VER
FILE=$NAME-$mpfr_VER$mpfr_PRIP
echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$C Rozbaluji soubory $DEF"
echo -e "$G tar xjpf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$C Presunuju soubory pro potreby GCC $DEF"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=gmp
PROGRAM=$NAME-$gmp_VER
FILE=$NAME-$gmp_VER$gmp_PRIP
echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$C Rozbaluji soubory $DEF"
echo -e "$G tar xjpf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$C Presunuju soubory pro potreby GCC $DEF"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=mpc
PROGRAM=$NAME-$mpc_VER
FILE=$NAME-$mpfr_VER$mpc_PRIP
echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$C Rozbaluji soubory $DEF"
echo -e "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$C Presunuju soubory pro potreby GCC $DEF"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT



NAME=gcc
PROGRAM=$NAME-$gcc_VER
FILE=$NAME-$gcc_VER$gcc_PRIP

source $SCRIPTS_DIR/include/initialization_separate_build

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM-BUILD
echo -e "$G ../$PROGRAM/configure $DEF" 
    ../$PROGRAM/configure --target=$LFS_TGT --prefix=/tools \
--disable-nls --disable-shared --disable-multilib \
--disable-decimal-float --disable-threads \
--disable-libmudflap --disable-libssp \
--disable-libgomp --enable-languages=c
    if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi
echo -e "$G make $DEF"
    make
    if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
echo -e "$G make-install $DEF"
    make install
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi

ln -vs libgcc.a `$LFS_TGT-gcc -print-libgcc-file-name | \
sed 's/libgcc/&_eh/'`

if [ $BUILD_RM == 1 ];
	then
                echo -e "$C Mazu slozku s buildem $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
                rm -rf $BUILD_DIR/$PROGRAM-BUILD
                echo -e "$C Mazu slozku se zdrojaky $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
                rm -rf $BUILD_DIR/$PROGRAM
				echo -e "$C Mazu slozku se zdrojaky gmp $DEF"
				echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
				rm -rf $BUILD_DIR/gmp
				echo -e "$C Mazu slozku se zdrojaky mpfr $DEF"
				echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
				rm -rf $BUILD_DIR/mpfr
	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi
cd $ROOT
