#!/bin/bash

NAME=dejagnu
PROGRAM=$NAME-$dejagnu_VER
FILE=$NAME-$dejagnu_VER$dejagnu_PRIP

unpackGzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	addPatch dejagnu-1.4.4-consolidated-1.patch

	c_Configure --prefix=/tools
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
	waitUser
	c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
	waitUser
	c_MakeTest check
	    if [ $? -ne 0 ]
			then
				echo -e "$L_FAIL_MAKC"
				exit 1
		fi
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
