#!/bin/bash

NAME=dejagnu
PROGRAM=$NAME-$dejagnu_VER
FILE=$NAME-$dejagnu_VER$dejagnu_PRIP

unpackGzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	addPatch dejagnu-1.4.4-consolidated-1.patch

	c_Configure --prefix=/tools || exit 1
	waitUser
	c_MakeInstall || exit 1
	waitUser
	c_MakeTest check || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
