#!/bin/bash

NAME=${dejagnu[0]}
PROGRAM=${dejagnu[3]}
FILE=${dejagnu[2]}
EXT=${dejagnu[4]}
DLINK=${dejagnu[1]}
MD5=${dejagnu[5]}
pFILE=${pdejangnu[1]}
pDLINK=${pdejangnu[0]}
pMD5=${pdejangnu[2]}

download ${DLINK}
download ${pDLINK}

waitUser

check ${FILE} ${MD5}
check ${pFILE} ${pMD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	addPatch ${pFILE}
	./configure --prefix=/tools || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	c_MakeTest check || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
