#!/bin/bash

NAME=diffutils
PROGRAM=$NAME-$diffutils_VER
FILE=$NAME-$diffutils_VER$diffutils_PRIP

source $SCRIPTS_DIR/include/unpack_gzip

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM
	echo -e "$G $PROGRAM/configure $DEF" 
      ./configure --prefix=/tools
	if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi

	echo -e "$G make $DEF"
	make
	if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi

	echo -e "$G make install $DEF"
	make install
	if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi

if [ $BUILD_RM == 1 ];
	then
		echo -e "$C Mazu slozku se zdrojaky $DEF"
        echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
        rm -rf $BUILD_DIR/$PROGRAM

	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi

cd $ROOT
