#!/bin/bash

NAME=${expect[0]}
PROGRAM=${expect[3]}
FILE=${expect[2]}
EXT=${expect[4]}
DLINK=${expect[1]}
MD5=${expect[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	cp -v configure{,.orig}
	sed 's:/usr/local/bin:/bin:' configure.orig > configure

	waitUser
	./configure --prefix=/tools --with-tcl=/tools/lib --with-tclinclude=/tools/include || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest test || exit 1
	waitUser    
	make SCRIPTS="" install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  

waitUser
RMsource
cd $ROOT
