#!/bin/bash

NAME=file
PROGRAM=$NAME-$file_VER
FILE=$NAME-$file_VER$file_PRIP

unpackGzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM
	c_Configure --prefix=/tools || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest check || exit 1
	waitUser
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
