#!/bin/bash

NAME=${findutils[0]}
PROGRAM=${findutils[3]}
FILE=${findutils[2]}
EXT=${findutils[4]}
DLINK=${findutils[1]}
MD5=${findutils[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild
cd $BUILD_DIR/$PROGRAM
{
  ./configure --prefix=/tools || exit 1
  waitUser
  c_Make || exit 1
  waitUser
  c_MakeTest check || exit 1
  waitUser
  c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
