#!/bin/bash
if [ $TOOLS_STRIP == 1 ];
   	then
		source $SCRIPTS_DIR/chap5/stripfiles
fi

echo -e "$L_CH_PRI $G /tools $DEF"
if [ "$UID" == 0 ]; 
	then
		echo -e "$L_CH_PRI $G /tools $DEF"
		chown -R root:root $TOOLS_DIR
	else
		echo -e "$L_CH_USRR $SCRIPTS_DIR/finish5 $DEF"
		exit 1
fi

echo -e "*******************************************************************"
echo -e "*******************************************************************"
echo -e "*******************************************************************"
echo -e "*********************** $L_DONE_CH5 *************************"
echo -e "********************** $L_DONE_CON ***********************"
echo -e "*************$SCRIPTS_DIR/chroot**************"
echo -e "*******************************************************************"
echo -e "*******************************************************************"
