#!/bin/bash
if [ $TOOLS_STRIP == 1 ];
   	then
		source $SCRIPTS_DIR/chap5/stripfiles
fi

echo -e "$L_CH_PRI $G /tools $DEF"
if [ "$UID" == 0 ]; 
	then
		echo -e "$L_CH_PRI $G /tools $DEF"
		chown -R root:root $TOOLS_DIR
	else
		echo -e "$C Log in as root and run $DEF"
		echo -e "$G chown -R root:root $LFS/tools $DEF"
		echo -e "$C than run $G $SCRIPTS_DIR/chap6/start6 $DEF"
		exit 1
fi
