#!/bin/bash

NAME=mpfr
PROGRAM=$NAME-$mpfr_VER
FILE=$NAME-$mpfr_VER$mpfr_PRIP
echo -e "$L_START_UNPACK $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$L_UN_SDIR"
echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$L_MV_FILGCC"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=gmp
PROGRAM=$NAME-$gmp_VER
FILE=$NAME-$gmp_VER$gmp_PRIP
echo -e "$L_START_UNPACK $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$L_UN_SDIR"
echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$L_MV_FILGCC"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=mpc
PROGRAM=$NAME-$mpc_VER
FILE=$NAME-$mpc_VER$mpc_PRIP
echo -e "$L_START_UNPACK $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$L_UN_SDIR"
echo -e "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$L_MV_FILGCC"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT



NAME=gcc
PROGRAM=$NAME-$gcc_VER
FILE=$NAME-$gcc_VER$gcc_PRIP

unpackBzipSep

waitUser

startBuild
{

cd $BUILD_DIR/$PROGRAM-BUILD
    c_ConfigureSep --target=$LFS_TGT --prefix=/tools --disable-nls --disable-shared --disable-multilib --disable-decimal-float --disable-threads --disable-libmudflap --disable-libssp --disable-libgomp --enable-languages=c --with-gmp-include=$(pwd)/gmp --with-gmp-lib=$(pwd)/gmp/.libs --without-ppl --without-cloog  || exit 1
    waitUser
    c_Make || exit 1
    waitUser
    c_MakeInstall || exit 1

ln -vs libgcc.a `$LFS_TGT-gcc -print-libgcc-file-name | sed 's/libgcc/&_eh/'`
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMbuild
echo -e "$L_RM_SDIR gmp"
echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
rm -rf $BUILD_DIR/gmp
echo -e "$L_RM_SDIR mpfr"
echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
rm -rf $BUILD_DIR/mpfr
echo -e "$L_RM_SDIR mpc"
echo -e "$G rm -rf $BUILD_DIR/mpc $DEF"
rm -rf $BUILD_DIR/mpc

cd $ROOT
