#!/bin/bash

NAME=${mpfr[0]}
PROGRAM=${mpfr[3]}
mpfr_dir=${mpfr[3]}
FILE=${mpfr[2]}
EXT=${mpfr[4]}
DLINK=${mpfr[1]}
MD5=${mpfr[5]}
echo -e "$L_START_UNPACK $PROGRAM $DEF"

waitUser

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

gccSupProgTest

echo -e "$L_UN_SDIR"
echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/

cd $ROOT

NAME=${gmp[0]}
PROGRAM=${gmp[3]}
gmp_dir=${gmp[3]}
FILE=${gmp[2]}
EXT=${gmp[4]}
DLINK=${gmp[1]}
MD5=${gmp[5]}
echo -e "$L_START_UNPACK $PROGRAM $DEF"

waitUser

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

gccSupProgTest

echo -e "$L_UN_SDIR"
echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/

cd $ROOT

NAME=${mpc[0]}
PROGRAM=${mpc[3]}
mpc_dir=${mpc[3]}
FILE=${mpc[2]}
EXT=${mpc[4]}
DLINK=${mpc[1]}
MD5=${mpc[5]}
echo -e "$L_START_UNPACK $PROGRAM $DEF"

waitUser

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

gccSupProgTest

echo -e "$L_UN_SDIR"
echo -e "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/

cd $ROOT



NAME=${gcc[0]}
PROGRAM=${gcc[3]}
FILE=${gcc[2]}
EXT=${gcc[4]}
DLINK=${gcc[1]}
MD5=${gcc[5]}

waitUser

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

SepBuild

waitUser

startBuild
{
echo -e "$L_MV_FILGCC"
mv -v $BUILD_DIR/$mpfr_dir $BUILD_DIR/$PROGRAM/mpfr
mv -v $BUILD_DIR/$gmp_dir $BUILD_DIR/$PROGRAM/gmp
mv -v $BUILD_DIR/$mpc_dir $BUILD_DIR/$PROGRAM/mpc
waitUser

cd $BUILD_DIR/$PROGRAM-BUILD
    ../gcc-4.5.2/configure \
    --target=$LFS_TGT --prefix=/tools \
    --disable-nls --disable-shared --disable-multilib \
    --disable-decimal-float --disable-threads \
    --disable-libmudflap --disable-libssp \
    --disable-libgomp --enable-languages=c \
    --with-gmp-include=$(pwd)/gmp --with-gmp-lib=$(pwd)/gmp/.libs \
    --without-ppl --without-cloog || exit 1
    waitUser
    c_Make || exit 1
    waitUser
    c_MakeInstall || exit 1

ln -vs libgcc.a `$LFS_TGT-gcc -print-libgcc-file-name | sed 's/libgcc/&_eh/'`

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMbuild
echo -e "$L_RM_SDIR gmp"
echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
rm -rf $BUILD_DIR/gmp
echo -e "$L_RM_SDIR mpfr"
echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
rm -rf $BUILD_DIR/mpfr
echo -e "$L_RM_SDIR mpc"
echo -e "$G rm -rf $BUILD_DIR/mpc $DEF"
rm -rf $BUILD_DIR/mpc

cd $ROOT
