#!/bin/bash

NAME=mpfr
PROGRAM=$NAME-$mpfr_VER
FILE=$NAME-$mpfr_VER$mpfr_PRIP
echo -e "$L_START_UNPACK $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$L_UN_SDIR"
echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$L_MV_FILGCC"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=gmp
PROGRAM=$NAME-$gmp_VER
FILE=$NAME-$gmp_VER$gmp_PRIP
echo -e "$L_START_UNPACK $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$L_UN_SDIR"
echo -e "$G tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$L_MV_FILGCC"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=mpc
PROGRAM=$NAME-$mpc_VER
FILE=$NAME-$mpc_VER$mpc_PRIP
echo -e "$L_START_UNPACK $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$L_RM_ASDIR"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$L_UN_SDIR"
echo -e "$G tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xzf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$L_MV_FILGCC"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT

NAME=gcc
PROGRAM=$NAME-$gcc_VER
FILE=$NAME-$gcc_VER$gcc_PRIP

unpackBzipSep

waitUser

startBuild

{
cd $BUILD_DIR/$PROGRAM

addPatch gcc-4.5.1-startfiles_fix-1.patch

cp -v gcc/Makefile.in{,.orig}
sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in
waitUser
cp -v gcc/Makefile.in{,.tmp}
sed 's/^T_CFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp > gcc/Makefile.in
waitUser
for file in \
 $(find gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
do
  cp -uv $file{,.orig}
  sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
  -e 's@/usr@/tools@g' $file.orig > $file
  echo '
#undef STANDARD_INCLUDE_DIR
#define STANDARD_INCLUDE_DIR 0
#define STANDARD_STARTFILE_PREFIX_1 ""
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
  touch $file.orig
done
waitUser
case $(uname -m) in
  x86_64)
    for file in $(find gcc/config -name t-linux64) ; do \
      cp -v $file{,.orig}
      sed '/MULTILIB_OSDIRNAMES/d' $file.orig > $file
    done
    waitUser
  ;;
esac

CC="$LFS_TGT-gcc -B/tools/lib/" 
AR=$LFS_TGT-ar 
RANLIB=$LFS_TGT-ranlib 
    c_ConfigureSep --prefix=/tools --with-local-prefix=/tools --enable-clocale=gnu --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-languages=c,c++ --disable-libstdcxx-pch --disable-multilib --disable-bootstrap --disable-libgomp --with-gmp-include=$(pwd)/gmp --with-gmp-lib=$(pwd)/gmp/.libs --without-ppl --without-cloog
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
	waitUser
	c_Make
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi
	waitUser
	c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
	waitUser
	ln -vs gcc /tools/bin/cc

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-P2.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  

waitUser
RMbuild
echo -e "$L_RM_SDIR gmp"
echo -e "$G rm -rf $BUILD_DIR/gmp $DEF"
rm -rf $BUILD_DIR/gmp
echo -e "$L_RM_SDIR mpfr"
echo -e "$G rm -rf $BUILD_DIR/mpfr $DEF"
rm -rf $BUILD_DIR/mpfr
echo -e "$L_RM_SDIR mpc"
echo -e "$G rm -rf $BUILD_DIR/mpc $DEF"
rm -rf $BUILD_DIR/mpc
cd $ROOT
