#!/bin/bash

NAME=gettext
PROGRAM=$NAME-$gettext_VER
FILE=$NAME-$gettext_VER$gettext_PRIP

unpackGzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM/gettext-tools
	c_Configure --prefix=/tools --disable-shared || exit 1
	waitUser
	c_Make -C gnulib-lib || exit 1
	waitUser
	c_Make -C src msgfmt || exit 1
	waitUser
	copyFiles src/msgfmt /tools/bin
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource

cd $ROOT
