#!/bin/bash

NAME=gettext
PROGRAM=$NAME-$gettext_VER
FILE=$NAME-$gettext_VER$gettext_PRIP

unpackGzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM/gettext-tools
	c_Configure --prefix=/tools --disable-shared
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
	waitUser
    c_Make -C gnulib-lib
	if [ $? -ne 0 ]
		then
			echo -e "$R make -C gnulib-lib [FAIL] $DEF"
			exit 1
	fi
	waitUser
    c_Make -C src msgfmt
	if [ $? -ne 0 ]
		then
			echo -e "$R make -C src msgfmt [FAIL] $DEF"
			exit 1
	fi
	waitUser
	copyFiles src/msgfmt /tools/bin
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource

cd $ROOT
