#!/bin/bash

NAME=${gettext[0]}
PROGRAM=${gettext[3]}
FILE=${gettext[2]}
EXT=${gettext[4]}
DLINK=${gettext[1]}
MD5=${gettext[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM/gettext-tools
	./configure --prefix=/tools --disable-shared || exit 1
	waitUser
	make -C gnulib-lib || exit 1
	waitUser
	make -C src msgfmt || exit 1
	waitUser
	copyFiles src/msgfmt /tools/bin
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource

cd $ROOT
