#!/bin/bash

NAME=${glibc[0]}
PROGRAM=${glibc[3]}
FILE=${glibc[2]}
EXT=${glibc[4]}
DLINK=${glibc[1]}
MD5=${glibc[5]}
pDLINK=${pglibc[0]}
pMD5=${pglibc[2]}
pPatch=${pglibc[1]}

download ${DLINK}
download ${pDLINK}

waitUser

check ${FILE} ${MD5}
check ${pPatch} ${pMD5}

waitUser

unpack ${EXT}

waitUser

SepBuild

waitUser

startBuild
cd $BUILD_DIR/$PROGRAM
{
	addPatch ${pPatch}

	waitUser
	cd $BUILD_DIR/$NAME-BUILD

	echo -e "$L_SET_CGLAG"
	case `uname -m` in
	  i?86) echo "CFLAGS += -march=i486 -mtune=native" > configparms ;;
	esac

	#SHELL=/bin/bash
	#CONFIG_SHELL=/bin/bash
	../$PROGRAM/configure --prefix=/tools --host=$LFS_TGT --build=$(../glibc-2.13/scripts/config.guess) --disable-profile --enable-add-ons --enable-kernel=2.6.22.5 --with-headers=/tools/include libc_cv_forced_unwind=yes libc_cv_c_cleanup=yes || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeInstall || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  

waitUser
RMbuild
cd $ROOT
