#!/bin/bash

NAME=glibc
PROGRAM=$NAME-$glibc_VER
FILE=$NAME-$glibc_VER$glibc_PRIP

unpackBzipSep

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM

{
	addPatch glibc-2.12.1-gcc_fix-1.patch

	addPatch glibc-2.12.1-makefile_fix-1.patch
waitUser
cd $BUILD_DIR/$PROGRAM-BUILD

      echo -e "$L_SET_CGLAG"
      case `uname -m` in
	i?86) echo "CFLAGS += -march=i486 -mtune=native" > configparms 
	waitUser ;;
      esac
	SHELL=/bin/bash
	CONFIG_SHELL=/bin/bash
	c_ConfigureSep --prefix=/tools --host=$LFS_TGT --build=$(../glibc-2.12.1/scripts/config.guess) --disable-profile --enable-add-ons --enable-kernel=2.6.22.5 --with-headers=/tools/include libc_cv_forced_unwind=yes libc_cv_c_cleanup=yes
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
      waitUser
    c_Make SHELL=/bin/bash
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi
      waitUser
    c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  

waitUser
RMbuild
cd $ROOT
