#!/bin/bash

NAME=gmp
PROGRAM=$NAME-$gmp_VER
FILE=$NAME-$gmp_VER$gmp_PRIP
echo -e "$Y Spousti se rozbaleni programu $PROGRAM $DEF"

if [ -d $BUILD_DIR/$PROGRAM ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$M.$DEF"
fi

if [ -d $BUILD_DIR/$NAME ];
	then
		echo -e "$C Slozka existuje mazu $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$NAME $DEF"
		rm -rf $BUILD_DIR/$NAME
	else
		echo -e "$M.$DEF"
fi

echo -e "$C Rozbaluji soubory $DEF"
echo -e "$G tar xjpf $SOURCES_DIR/$FILE -C $BUILD_DIR/ $DEF"
tar xjf $SOURCES_DIR/$FILE -C $BUILD_DIR/
echo -e "$C Presunuju soubory pro potreby GCC $DEF"
echo -e "$G mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME $DEF"
mv $BUILD_DIR/$PROGRAM $BUILD_DIR/$NAME

cd $ROOT
