#!/bin/bash

NAME=${gzip[0]}
PROGRAM=${gzip[3]}
FILE=${gzip[2]}
EXT=${gzip[4]}
DLINK=${gzip[1]}
MD5=${gzip[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	./configure --prefix=/tools || exit 1
	StartMake
	waitUser
	make || exit 1
	waitUser
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
