#!/bin/bash

echo -e "$L_TEST_SPR"
cd $TOOLS_DIR
{
echo 'main(){}' > dummy.c
cc dummy.c

readelf -l a.out | grep ': /tools' > testlink.2

case $(uname -m) in
    x86_64) compareFiles $SCRIPTS_DIR/linker.1.test64 $TOOLS_DIR/testlink.2 ;;
    i?86) compareFiles $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.2 ;; 
esac
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  

echo -e "$L_RM_TFIL $DEF $G /tools/dummy.c, /tools/a.out $DEF"
rm -r $TOOLS_DIR/dummy.c $TOOLS_DIR/a.out
echo -e "$G $TOOLS_DIR/testlink.2 $DEF $L_SET_KEEP"

cd $ROOT
