#!/bin/bash

echo -e "$Y Oddeleni Toolchainu $DEF"

echo -e "$C Nastavuji linker $DEF"
cd $TOOLS_DIR
SPECS=`dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/specs
$LFS_TGT-gcc -dumpspecs | sed -e 's@/lib\(64\)\?/ld@/tools&@g' -e "/^\*cpp:$/{n;s,$, -isystem /tools/include,}" > $SPECS
echo "Nový specs soubor je: $SPECS"
unset SPECS


echo -e "$Y Testuju spravnost $DEF"

echo 'main(){}' > dummy.c
$LFS_TGT-gcc -B/tools/lib dummy.c

readelf -l a.out | grep ': /tools' > testlink.1

if cmp $SCRIPTS_DIR/linker.1.test $TOOLS_DIR/testlink.1 &> /dev/null
	then
		echo -e "$C Linker test $G [OK] $DEF"
	else
		echo -e "$C Linker test $R [FAIL] $DEF"
		echo -e "$R Je treba uzivatelske interakce [Prerusuji] $DEF"
		exit 1
fi
echo -e "$C Mazu docasne soubory $DEF $G /tools/dummy.c, /tools/a.out $DEF"
rm -r $TOOLS_DIR/dummy.c $TOOLS_DIR/a.out
echo -e "$C Pro kontrolu je nechan soubor $DEF $G $TOOLS_DIR/testlink.1 $DEF"
sleep 10

cd $ROOT
