#!/bin/bash

NAME=linux
PROGRAM=$NAME-$linux_VER
FILE=$NAME-$linux_VER$linux_PRIP

unpackBzip

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
    c_Make mrproper
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MMRP"
			exit 1
	fi
      waitUser
    c_Make headers_check
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MHCH"
			exit 1
	fi
      waitUser
    c_Make INSTALL_HDR_PATH=dest headers_install
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
	waitUser
	copyFilesRec dest/include/* /tools/include
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
