#!/bin/bash

NAME=${linux[0]}
PROGRAM=${linux[3]}
FILE=${linux[2]}
EXT=${linux[4]}
DLINK=${linux[1]}
MD5=${linux[5]}


download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	make mrproper || exit 1
	waitUser
	make headers_check || exit 1
	waitUser
	make INSTALL_HDR_PATH=dest headers_install || exit 1
	waitUser
	copyFilesRec dest/include/* /tools/include

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
