#!/bin/bash

NAME=m4
PROGRAM=$NAME-$m4_VER
FILE=$NAME-$m4_VER$m4_PRIP

unpackBzip

waitUser

startBuild
{
	cd $BUILD_DIR/$PROGRAM

	sed -i -e '/"m4.h"/a #include <sys/stat.h>' src/path.c
	waitUser
	c_Configure --prefix=/tools || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest check || exit 1
	waitUser
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
