#!/bin/bash

NAME=make
PROGRAM=$NAME-$make_VER
FILE=$NAME-$make_VER$make_PRIP

source $SCRIPTS_DIR/include/unpack_bzip

echo -e "$Y Spoustim Build $DEF"
{
cd $BUILD_DIR/$PROGRAM
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/tools
    if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi

    echo -e "$G make $DEF"
    make
    if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
	
	if [ $BUILD_TEST == 1 ] || [ $BUILD_TEST == 3 ];
    	then
			echo -e "$G make check $DEF"
			make check
			if [ $? -ne 0 ]
				then
					echo -e "$R make check $DEF"
					exit 1
			fi
	fi
	
    echo -e "$G make-install $DEF"
    make install
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$R build selhal $DEF"
		exit 1
fi  
if [ $BUILD_RM == 1 ];
	then
		echo -e "$C Mazu slozku se zdrojaky $DEF"
		echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
		rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi

cd $ROOT
