#!/bin/bash

NAME=${ncurses[0]}
PROGRAM=${ncurses[3]}
FILE=${ncurses[2]}
EXT=${ncurses[4]}
DLINK=${ncurses[1]}
MD5=${ncurses[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM
	./configure --prefix=/tools --with-shared \
    --without-debug --without-ada --enable-overwrite || exit 1
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
