#!/bin/bash

NAME=ncurses
PROGRAM=$NAME-$ncurses_VER
FILE=$NAME-$ncurses_VER$ncurses_PRIP

unpackGzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM
	c_Configure --prefix=/tools --with-shared --without-debug --without-ada --enable-overwrite
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi

	c_Make
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi

	c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
