#!/bin/bash

NAME=patch
PROGRAM=$NAME-$patch_VER
FILE=$NAME-$patch_VER$patch_PRIP

unpackBzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM
	c_Configure --prefix=/tools || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest check || exit 1
	waitUser
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
