#!/bin/bash

NAME=${perl[0]}
PROGRAM=${perl[3]}
FILE=${perl[2]}
EXT=${perl[4]}
DLINK=${perl[1]}
MD5=${perl[5]}
pFILE=${pperl[1]}
pDLINK=${pperl[0]}
pMD5=${pperl[2]}

download ${DLINK}
download ${pDLINK}

waitUser

check ${FILE} ${MD5}
check ${pFILE} ${pMD5}

waitUser

unpack ${EXT}

startBuild
waitUser
{
cd $BUILD_DIR/$PROGRAM
	addPatch ${pFILE}
	waitUser
	echo -e "$G $PROGRAM/Configure $DEF"
	$BUILD_DIR/$PROGRAM/Configure -des -Dprefix=/tools \
                  -Dstatic_ext='Data/Dumper Fcntl IO' || exit 1
	StartMake perl utilities ext/Errno/pm_to_blib
	waitUser
	make perl utilities ext/Errno/pm_to_blib || exit 1
	echo -e "$L_COP_FILES"
	echo -e "$G cp -v perl pod/pod2man /tools/bin $DEF"
	waitUser
	cp -v perl pod/pod2man /tools/bin
	echo -e "$C Making directory $G /tools/lib/perl5/5.12.3 $DEF"
	waitUser
	mkdir -pv /tools/lib/perl5/5.12.3
	echo -e "$L_COP_FILES"
	echo -e "$G cp -Rv lib/* /tools/lib/perl5/5.12.3 $DEF"
	waitUser
	cp -Rv lib/* /tools/lib/perl5/5.12.3

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
