#!/bin/bash

NAME=sed
PROGRAM=$NAME-$sed_VER
FILE=$NAME-$sed_VER$sed_PRIP

unpackBzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM
	c_Configure --prefix=/tools
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
    waitUser
    c_Make
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi
	waitUser
	c_MakeTest check
	if [ $? -ne 0 ]
	  then
		echo -e "$L_FAIL_MAKC"
		exit 1
	fi
	waitUser
	c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
