#!/bin/bash

echo -e "$L_VAR_VEL"

echo -e "$L_RM_UF"
echo -e "$G strip --strip-debug /tools/lib/* $DEF"
strip --strip-debug /tools/lib/*

echo -e "$L_RM_UF"
echo -e "$G strip --strip-unneeded /tools/{,s}bin/* $DEF"
strip --strip-unneeded /tools/{,s}bin/*

echo -e "$L_RM_FL"
echo -e "$G rm -rf /tools/{,share}/{info,man} $DEF"
rm -rf /tools/{,share}/{info,man}
