#!/bin/bash

NAME=tar
PROGRAM=$NAME-$tar_VER
FILE=$NAME-$tar_VER$tar_PRIP

unpackBzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM

	sed -i /SIGPIPE/d src/tar.c
	waitUser
	c_Configure --prefix=/tools || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest check || exit 1
	waitUser
	c_MakeTest || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
