#!/bin/bash

NAME=${tar[0]}
PROGRAM=${tar[3]}
FILE=${tar[2]}
EXT=${tar[4]}
DLINK=${tar[1]}
MD5=${tar[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	./configure --prefix=/tools || exit 1
	StartMake
	waitUser
	make || exit 1
	waitUser
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
