#!/bin/bash

NAME=tar
PROGRAM=$NAME-$tar_VER
FILE=$NAME-$tar_VER$tar_PRIP

unpackBzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM

	sed -i /SIGPIPE/d src/tar.c
	waitUser
	c_Configure --prefix=/tools
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
	waitUser
	c_Make
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi
	waitUser
	c_MakeTest check
	if [ $? -ne 0 ]
	  then
		echo -e "$L_FAIL_MAKC"
		exit 1
	fi
	waitUser
	c_MakeTest
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
