#!/bin/bash

NAME=tcl
PROGRAM=$NAME$tcl_VER2
FILE=$NAME$tcl_VER$tcl_PRIP

unpackGzip

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM/unix
    
    c_Configure --prefix=/tools
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_CONF"
			exit 1
	fi
    waitUser
    c_Make
    if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKE"
			exit 1
	fi
	waitUser
	TZ=UTC
	c_Make test
	if [ $? -ne 0 ]
	  then
	      echo -e "$L_FAIL_MAKT"
	      exit 1
	fi
	waitUser
	c_MakeInstall
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKA"
			exit 1
	fi
	waitUser
	echo -e "$L_CH_PRI $G /tools/lib/libtcl8.5.so $DEF"
	echo -e "$G chmod -v u+w /tools/lib/libtcl8.5.so $DEF"
	chmod -v u+w /tools/lib/libtcl8.5.so
	waitUser
	c_Make install-private-headers
	if [ $? -ne 0 ]
		then
			echo -e "$L_FAIL_MAKT $R install-private-headers $DEF"
			exit 1
	fi
	echo -e "$L_MK_LNS"
	echo -e "$G ln -sv tclsh8.5 /tools/bin/tclsh $DEF"
	ln -sv tclsh8.5 /tools/bin/tclsh
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
