#!/bin/bash

NAME=${tcl[0]}
PROGRAM=${tcl[3]}
FILE=${tcl[2]}
EXT=${tcl[4]}
DLINK=${tcl[1]}
MD5=${tcl[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild
{
cd $BUILD_DIR/$PROGRAM/unix
    
	./configure --prefix=/tools || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	TZ=UTC
	c_Make test || exit 1
	waitUser
	c_MakeInstall || exit 1
	waitUser
	echo -e "$L_CH_PRI $G /tools/lib/libtcl8.5.so $DEF"
	echo -e "$G chmod -v u+w /tools/lib/libtcl8.5.so $DEF"
	chmod -v u+w /tools/lib/libtcl8.5.so
	waitUser
	c_Make install-private-headers || exit 1
	echo -e "$L_MK_LNS"
	echo -e "$G ln -sv tclsh8.5 /tools/bin/tclsh $DEF"
	ln -sv tclsh8.5 /tools/bin/tclsh
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
