#!/bin/bash

NAME=tcl
PROGRAM=$NAME$tcl_VER2
FILE=$NAME$tcl_VER$tcl_PRIP

source $SCRIPTS_DIR/include/unpack_gzip

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM/unix
	echo -e "$G $PROGRAM/configure $DEF" 
    ./configure --prefix=/tools
    if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi

    echo -e "$G make $DEF"
    make
    if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
	
	if [ $BUILD_TEST == 1 ] || [ $BUILD_TEST == 3 ];
		then
	    echo -e "$G make test $DEF"
	    TZ=UTC make test
	    if [ $? -ne 0 ]
			then
				echo -e "$R make selhalo $DEF"
				exit 1
		fi
	fi
	
    echo -e "$G make-install $DEF"
    make install
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi
	echo -e "$C menim prava $G /tools/lib/libtcl8.5.so $DEF"
	echo -e "$G chmod -v u+w /tools/lib/libtcl8.5.so $DEF"
	chmod -v u+w /tools/lib/libtcl8.5.so
	
	echo -e "$G make install-private-headers $DEF"
    make install-private-headers
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi
	echo -e "$C Vytvarim potrebny symbolicky odkaz $DEF"
	echo -e "$G ln -sv tclsh8.5 /tools/bin/tclsh $DEF"
	ln -sv tclsh8.5 /tools/bin/tclsh

	if [ $BUILD_RM == 1 ];
		then
			echo -e "$C Mazu slozku se zdrojaky $DEF"
			echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
			rm -rf $BUILD_DIR/$PROGRAM

		else
			echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
	fi
cd $ROOT
