#!/bin/bash

NAME=${texinfo[0]}
PROGRAM=${texinfo[3]}
FILE=${texinfo[2]}
EXT=${texinfo[4]}
DLINK=${texinfo[1]}
MD5=${texinfo[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	./configure --prefix=/tools || exit 1
	waitUser
	c_Make || exit 1
	waitUser
	c_MakeTest check || exit 1
	waitUser
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
