#!/bin/bash

source ./variables
source $SCRIPTS_DIR/include/functions

NAME=dhcpcd
PROGRAM=dhcpcd-4.0.11
FILE=dhcpcd-4.0.11.tar.bz2
EXT=bzip
DLINK=ftp://ftp.osuosl.org/pub/gentoo/distfiles/${FILE}
MD5=b9f1ccdaaf23ffea7dd6fd89e932f4ed

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	StartMake
	waitUser
	make PREFIX= \
      LIBEXECDIR=/lib/dhcpcd \
      DBDIR=/var/lib/dhcpcd \
      SYSCONFDIR=/etc/dhcpcd || exit 1
	StartMakeInstall
	waitUser
	make PREFIX= \
      LIBEXECDIR=/lib/dhcpcd \
      DBDIR=/var/lib/dhcpcd \
      SYSCONFDIR=/etc/dhcpcd install

sed -i "s;/var/lib/dhcpcd-;/var/lib/dhcpcd/dhcpcd-;g" \
       dhcpcd-hooks/50-dhcpcd-compat &&
install -v -m 644 dhcpcd-hooks/50-dhcpcd-compat /lib/dhcpcd/dhcpcd-hooks/

make install-service-dhcpcd

install -v -d /etc/sysconfig/network-devices/ifconfig.eth0 &&
cat > /etc/sysconfig/network-devices/ifconfig.eth0/dhcpcd << "EOF"
ONBOOT="yes"
SERVICE="dhcpcd"
DHCP_START=""
DHCP_STOP="-k"

# Set PRINTIP="yes" to have the script print
# the DHCP assigned IP address
PRINTIP="no"

# Set PRINTALL="yes" to print the DHCP assigned values for
# IP, SM, DG, and 1st NS. This requires PRINTIP="yes".
PRINTALL="no"
EOF

cat > /etc/dhclient.conf << "EOF"
# dhclient.conf

interface "eth0"{
prepend domain-name-servers 127.0.0.1;
request subnet-mask, broadcast-address, time-offset, routers,
        domain-name, domain-name-servers, host-name;
require subnet-mask, domain-name-servers;
}
# end dhclient.conf
EOF


} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
