#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions


NAME=expat
PROGRAM=expat-2.0.1
FILE=expat-2.0.1.tar.gz
EXT=gzip
DLINK=http://downloads.sourceforge.net/expat/${FILE}
pFILE=expat-2.0.1-fixes-3.patch
pDLINK=http://www.linuxfromscratch.org/patches/blfs/svn/${pFILE}
MD5=ee8b492592568805593f81f8cdf2a04c

download ${DLINK}
download ${pDLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{
patch -Np1 -i $SOURCES_DIR/$pFILE
	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
install -v -m755 -d /usr/share/doc/expat-2.0.1
install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat-2.0.1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
