#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=gperf
PROGRAM=gperf-3.0.4
FILE=gperf-3.0.4.tar.gz
EXT=gzip
DLINK=http://ftp.gnu.org/gnu/gperf/${FILE}
pFILE=Python-2.6.4-bdb_4.8-1.patch
pDLINK=http://www.linuxfromscratch.org/patches/blfs/svn/${pFILE}
MD5=c1f1db32fb6598d6a93e6e88796a8632

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
/configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.0.4
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1

install -m644 -v doc/gperf.{dvi,ps,pdf,txt} \
                 /usr/share/doc/gperf-3.0.4

pushd /usr/share/info
rm -v dir
for FILENAME in *; do
    install-info $FILENAME dir 2>/dev/null
done
popd

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
