#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

source $SCRIPTS_DIR/BLFS/XMLParser

NAME=intltool
PROGRAM=intltool-0.41.1
FILE=intltool-0.41.1.tar.gz
EXT=gzip
DLINK=http://launchpad.net/intltool/trunk/0.41.1/+download/${FILE}
MD5=d6c91bf06681919ccfdf3624035b75dc

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
install -v -m644 -D doc/I18N-HOWTO \
    /usr/share/doc/intltool-0.41.1/I18N-HOWTO
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
