#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

source $SCRIPTS_DIR/BLFS/cairo

NAME=libdrm
PROGRAM=libdrm-2.4.23
FILE=libdrm-2.4.23.tar.bz2
EXT=bzip
DLINK=http://dri.freedesktop.org/libdrm/${FILE}
MD5=7577ff36ec364d88fae466d4f7fc5fc6

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=$XORG_PREFIX
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
