#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=libpng
PROGRAM=libpng-1.2.44
FILE=libpng-1.2.44.tar.bz2
EXT=bzip
DLINK=http://downloads.sourceforge.net/libpng/${FILE}
MD5=e3ac7879d62ad166a6f0c7441390d12b

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1
install -v -m755 -d /usr/share/doc/libpng-1.2.44
install -v -m644    README libpng-1.2.44.txt \
                    /usr/share/doc/libpng-1.2.44

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
