#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=Python
PROGRAM=Python-2.6.4
FILE=Python-2.6.4.tar.bz2
EXT=bzip
DLINK=http://www.python.org/ftp/python/2.6.4/${FILE}
pFILE=Python-2.6.4-bdb_4.8-1.patch
pDLINK=http://www.linuxfromscratch.org/patches/blfs/svn/${pFILE}
MD5=fee5408634a54e721a93531aba37f8c1

download ${DLINK}
download ${pDLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{
sed -i "s/ndbm_libs = \[\]/ndbm_libs = ['gdbm', 'gdbm_compat']/" \
     setup.py &&
patch -Np1 -i $SOURCES_DIR/$pFILE

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr --enable-shared
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
chmod -v 755 /usr/lib/libpython2.6.so.1.0

echo "export PYTHONDOCS=/usr/share/doc/Python-2.6.4/html" >> ~/.bashrc

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
