#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=wget
PROGRAM=wget-1.12
FILE=wget-1.12.tar.bz2
EXT=bzip
DLINK=http://ftp.gnu.org/gnu/wget/${FILE}
MD5=308a5476fc096a8a525d07279a6f6aa3

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
	./configure --prefix=/usr --sysconfdir=/etc

	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 
RMsource

cd $ROOT
