#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions


NAME=XML-Parser
PROGRAM=XML-Parser-2.40
FILE=XML-Parser-2.40.tar.gz
EXT=gzip
DLINK=http://www.cpan.org/authors/id/C/CH/CHORNY/${FILE}

download ${DLINK}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G perl Makefile.PL  $DEF"
perl Makefile.PL

	StartMake
	waitUser
	make || exit 1

	make test || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
