#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

source $SCRIPTS_DIR/BLFS/xorgdir/prexorg
source $SCRIPTS_DIR/BLFS/xorgdir/util-macros
source $SCRIPTS_DIR/BLFS/xorgdir/proto
source $SCRIPTS_DIR/BLFS/xorgdir/makedepend
source $SCRIPTS_DIR/BLFS/xorgdir/libxau
source $SCRIPTS_DIR/BLFS/xorgdir/libxdmcp
source $SCRIPTS_DIR/BLFS/xorgdir/libpthread
source $SCRIPTS_DIR/BLFS/xorgdir/xcb
source $SCRIPTS_DIR/BLFS/xorgdir/libxcb
source $SCRIPTS_DIR/BLFS/xorgdir/xorglib
source $SCRIPTS_DIR/BLFS/xorgdir/xcbutil
source $SCRIPTS_DIR/BLFS/xorgdir/mesalib
source $SCRIPTS_DIR/BLFS/xorgdir/xorgapp
source $SCRIPTS_DIR/BLFS/xorgdir/xcursor
source $SCRIPTS_DIR/BLFS/xorgdir/xfonts
source $SCRIPTS_DIR/BLFS/xorgdir/xkeyboard
source $SCRIPTS_DIR/BLFS/xorgdir/xorgserver
source $SCRIPTS_DIR/BLFS/xorgdir/xdrivers
source $SCRIPTS_DIR/BLFS/xorgdir/xtermandset

