#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=freeglut
PROGRAM=freeglut-2.6.0
FILE=freeglut-2.6.0.tar.gz
EXT=gzip
DLINK=http://downloads.sourceforge.net/freeglut/${FILE}
MD5=39f0f2de89f399529d2b981188082218

download ${DLINK}
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1
install -v -D -m644 doc/freeglut_user_interface.html \
    /usr/share/doc/freeglut-2.6.0/freeglut_user_interface.html
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
