#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions
source $SCRIPTS_DIR/BLFS/tint/libjpeg

NAME=imlib2
PROGRAM=imlib2-1.4.4
FILE=imlib2-1.4.4.tar.bz2
EXT=bzip
DLINK=http://downloads.sourceforge.net/enlightenment/${FILE}
MD5=b6de51879502e857d5b1f7622267a030

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1

install -v -m755 -d /usr/share/doc/imlib2-1.4.4
install -v -m644    doc/{*.gif,index.html} \
                    /usr/share/doc/imlib2-1.4.4

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
