#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=jbigkit
PROGRAM=jbigkit
FILE=jbigkit-2.0.tar.gz
EXT=gzip
DLINK=http://www.cl.cam.ac.uk/~mgk25/download/${FILE}
MD5=39f0f2de89f399529d2b981188082218

download ${DLINK}
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	StartMake
	waitUser
	make CC="gcc -fPIC" || exit 1

install -m755 pbmtools/{jbgtopbm,pbmtojbg} /usr/bin
install -m644 libjbig/jbig.h /usr/include
install -m644 libjbig/libjbig.a /usr/lib

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
