#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions
source $SCRIPTS_DIR/BLFS/tint/freeglut

NAME=tiff
PROGRAM=tiff-3.9.4
FILE=tiff-3.9.4.tar.gz
EXT=gzip
DLINK=http://download.osgeo.org/libtiff/${FILE}
MD5=2006c1bdd12644dbf02956955175afd6

download ${DLINK}
check ${FILE} ${MD5}
waitUser
unpack ${EXT}

cd $BUILD_DIR/$PROGRAM
{

	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure --prefix=/usr
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	 

RMsource

cd $ROOT
