#!/bin/bash
set +h
set -e

for NIC in /sys/class/net/* ; do
    INTERFACE=${NIC##*/} udevadm test --action=add $NIC
done
cat /etc/udev/rules.d/70-persistent-net.rules
cd /etc/sysconfig/network-devices
mkdir -v ifconfig.eth0
cat > ifconfig.eth0/ipv4 << "EOF"
ONBOOT=yes
SERVICE=ipv4-static
IP=192.168.1.1
GATEWAY=192.168.1.2
PREFIX=24
BROADCAST=192.168.1.255
EOF
cat > /etc/resolv.conf << "EOF"
# Begin /etc/resolv.conf

domain **EDITME<Your Domain Name>EDITME**
nameserver **EDITME<IP address of your primary nameserver>EDITME**
nameserver **EDITME<IP address of your secondary nameserver>EDITME**

# End /etc/resolv.conf
EOF
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
