#!/bin/bash

echo -e "$C List of locales $DEF"
locale -a

echo -e "$C type you locale and pres enter, exampe $G en_us.utf8"
read vaLocale
LC_ALL=$vaLocale locale charmap
LC_ALL=$vaLocale locale language
LC_ALL=$vaLocale locale charmap
LC_ALL=$vaLocale locale int_curr_symbol
LC_ALL=$vaLocale locale int_prefix

echo -e "$C Change variable LANG later for other language $DEF"
echo "# Begin /etc/profile"  > /etc/profile
echo "" >> /etc/profile
echo "export LANG=${vaLocale}" >> /etc/profile
echo "" >> /etc/profile
echo "# End /etc/profile" >> /etc/profile


