#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=libpthread-stubs
PROGRAM=libpthread-stubs-0.3
FILE=libpthread-stubs-0.3.tar.bz2
EXT=bzip
DLINK=http://xcb.freedesktop.org/dist/${FILE}
MD5=e8fa31b42e13f87e8f5a7a2b731db7ee

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}
cd $BUILD_DIR/$PROGRAM
	echo "$G $PROGRAM/configure   $DEF"
	waitUser
./configure $XORG_CONFIG
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1

cd $ROOT

