#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=Xorg-Libraries
md5DLINK=http://anduin.linuxfromscratch.org/files/BLFS/svn/xorg/lib-7.6-1.md5
wgetDLINK=http://anduin.linuxfromscratch.org/files/BLFS/svn/xorg/lib-7.6-1.wget

download ${md5DLINK}
download ${wgetDLINK}
waitUser
cd $BUILD_DIR

mkdir lib
cd lib
grep -v '^#' $SOURCES_DIR/lib-7.6-1.wget | wget -i- -c \
    -B http://xorg.freedesktop.org/releases/individual/lib/
md5sum -c $SOURCES_DIR/lib-7.6-1.md5
waitUser
for package in $(grep -v '^#' $SOURCES_DIR/lib-7.6-1.wget)
do
  packagedir=${package%.tar.bz2}
  tar -xf $package
  cd $packagedir
  case "$packagedir" in
	libXfont-[0-9]* )
		         ./configure $XORG_CONFIG --disable-devel-docs
		         ;;
	   libXt-[0-9]* )
		         ./configure $XORG_CONFIG \
		             --with-appdefaultdir=/etc/X11/app-defaults
		         ;;
		      * )
		         ./configure $XORG_CONFIG
		         ;;
	esac
  make
  make install
  unset CONFIGPARAMS
  ldconfig
  cd ..
  rm -rf $packagedir
  waitUser
done 2>&1 | tee -a ../lib-7.5-2-compile.log

ln -sv $XORG_PREFIX/lib/X11 /usr/lib/X11
ln -sv $XORG_PREFIX/include/X11 /usr/include/X11
ln -sv $XORG_PREFIX /usr/X11R6
waitUser
cd $ROOT

