#!/bin/bash

source /scripts/BLFS/variables

source $SCRIPTS_DIR/include/functions

NAME=xterm
PROGRAM=xterm-267
FILE=xterm-267.tgz
EXT=bzip
DLINK=ftp://invisible-island.net/xterm/${FILE}
MD5=3945ab70cfa2a9e95804157ee1b0f8e8

download ${DLINK}
waitUser
check ${FILE} ${MD5}
waitUser
unpack ${EXT}
cd $BUILD_DIR/$PROGRAM
sed -i '/v0/,+1s/new:/new:kb=^?:/' termcap
echo -e '\tkbs=\\177,' >>terminfo
TERMINFO=/usr/lib/terminfo ./configure $XORG_CONFIG \
    --enable-luit --enable-wide-chars \
    --with-app-defaults=/etc/X11/app-defaults
	StartMake
	waitUser
	make || exit 1

	StartMakeInstall
	waitUser
	make install || exit 1
waitUser
	make install-ti
waitUser
cat >> /etc/X11/app-defaults/XTerm << "EOF"
*VT100*locale: true
*VT100*faceName: Monospace
*VT100*faceSize: 10
*backarrowKeyIsErase: true
*ptyInitialErase: true
EOF

cd $ROOT

#ln -vsf <$XORG_PREFIX> /usr/X11R6
#waitUser
cd ~
Xorg -configure
waitUser
X -retro -config ~/xorg.conf.new
waitUser
install -v -m644 ~/xorg.conf.new /etc/X11/xorg.conf
waitUser
cat > ~/.xinitrc << "EOF"
# Begin .xinitrc file
xterm  -g 80x40+0+0   &
xclock -g 100x100-0+0 &
twm
EOF

cat >> /etc/sysconfig/createfiles << "EOF"
/tmp/.ICE-unix dir 1777 root root
EOF


