#!/bin/bash
set +h
set -e

cd $PKGDIR
make mrproper
cp -v ../kernel-config .config
make
make modules_install
cp -v arch/x86/boot/bzImage /boot/vmlinux-2.6.38.6-lfs-SVN-20110515
cp -v System.map /boot/System.map-2.6.38.6
cp -v .config /boot/config-2.6.38.6
install -d /usr/share/doc/linux-2.6.38.6
cp -r Documentation/* /usr/share/doc/linux-2.6.38.6
install -v -m755 -d /etc/modprobe.d
cat > /etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
