#!/bin/bash

NAME=${linux[0]}
PROGRAM=${linux[3]}
FILE=${linux[2]}
EXT=${linux[4]}
DLINK=${linux[1]}
MD5=${linux[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild
{
	echo -e "$G make mrproper $DEF"
	make mrproper
	echo -e "$G make LANG=en_US.utf8 LC_ALL= menuconfig $DEF"	
	waitUser
	make LANG=en_US.utf8 LC_ALL= menuconfig
	echo -e "$G make $DEF"
	waitUser
	make
	waitUser
	echo -e "$G make modules_install $DEF"
	make modules_install
	echo -e "$G cp -v arch/x86/boot/bzImage /boot/vmlinux-2.6.37-lfs-6.8 $DEF"
	waitUser
	cp -v arch/x86/boot/bzImage /boot/vmlinux-2.6.37-lfs-6.8
	echo -e "$G cp -v System.map /boot/System.map-2.6.37 $DEF"
	waitUser
	cp -v System.map /boot/System.map-2.6.37
	echo -e "$G cp -v .config /boot/config-2.6.37 $DEF"	
	waitUser
	cp -v .config /boot/config-2.6.37
	echo -e "$G install -d /usr/share/doc/linux-2.6.37 $DEF"
	waitUser
	install -d /usr/share/doc/linux-2.6.37
	echo -e "$G cp -r Documentation/* /usr/share/doc/linux-2.6.37 $DEF"
	waitUser
	cp -r Documentation/* /usr/share/doc/linux-2.6.37
	echo -e "$G install -v -m755 -d /etc/modprobe.d $DEF"
	waitUser
	install -v -m755 -d /etc/modprobe.d
	echo -e "$C Making File $G /etc/modprobe.d/usb.conf $DEF"
	waitUser
	cat > /etc/modprobe.d/usb.conf << "EOF"
	# Begin /etc/modprobe.d/usb.conf

	install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
	install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

	# End /etc/modprobe.d/usb.conf
	EOF
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-ch6.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$R build selhal $DEF"
		exit 1
fi  
