#!/bin/bash

#definice barev
export K="\033[0;30m"    # black
export R="\033[0;31m"    # red
export G="\033[0;32m"    # green
export Y="\033[0;33m"    # yellow
export B="\033[0;34m"    # blue
export M="\033[0;35m"    # magenta
export C="\033[0;36m"    # cyan
export W="\033[0;37m"    # white
export DEF="\033[0m"     # predchozi barva