#!/bin/bash


export TOOLS_STRIP=0 # 1=tools strip
export WAIT=0
export MakeTests=0
export on64=0 #only if you building 32bit on 64bit machine

export ROOT=/mnt/LFS	#mount point
export LFS=$ROOT
export LC_ALL=POSIX
export LFS_TGT=$(uname -m)-lfs-linux-gnu
export PATH=/tools/bin:/bin:/usr/bin
export MAKEFLAGS='-j 3' #number of procesor cores

export SOURCES_DIR=$ROOT/sources
export BUILD_DIR=$ROOT/build
export TOOLS_DIR=$ROOT/tools
export SCRIPTS_DIR=$ROOT/scripts

echo -e "$L_CH_DIR"

testExDir $SOURCES_DIR
testExDir $BUILD_DIR
testExDir $TOOLS_DIR
testExDir $SCRIPTS_DIR
testSimLink /tools $LFS/tools /
cd $ROOT
