#!/bin/bash

NAME=${automake[0]}
PROGRAM=${automake[3]}
FILE=${automake[2]}
EXT=${automake[4]}
DLINK=${automake[1]}
MD5=${automake[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.11.1 || exit 1

	c_Make || exit 1
	
	c_MakeTest check || exit 1
	
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
