#!/bin/bash

NAME=${findutils[0]}
PROGRAM=${findutils[3]}
FILE=${findutils[2]}
EXT=${findutils[4]}
DLINK=${findutils[1]}
MD5=${findutils[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --libexecdir=/usr/lib/findutils \
    --localstatedir=/var/lib/locate || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1

mv -v /usr/bin/find /bin
sed -i 's/find:=${BINDIR}/find:=\/bin/' /usr/bin/updatedb

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
