#!/bin/bash

NAME=${flex[0]}
PROGRAM=${flex[3]}
FILE=${flex[2]}
EXT=${flex[4]}
DLINK=${flex[1]}
MD5=${flex[5]}
pFILE=${pflex[1]}
pDLINK=${pflex[0]}
pMD5=${pflex[2]}

download ${DLINK}
download ${pDLINK}

waitUser

check ${FILE} ${MD5}
check ${pFILE} ${pMD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	addPatch ${pFILE}
	waitUser
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	ln -sv libfl.a /usr/lib/libl.a
	waitUser
echo -e "$L_MK_FIL"
cat > /usr/bin/lex << "EOF"
#!/bin/sh
# Begin /usr/bin/lex

exec /usr/bin/flex -l "$@"

# End /usr/bin/lex
EOF
chmod -v 755 /usr/bin/lex
waitUser
mkdir -v /usr/share/doc/flex-2.5.35
cp    -v doc/flex.pdf \
         /usr/share/doc/flex-2.5.35

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
