#!/bin/bash

NAME=glibc
PROGRAM=$NAME-$glibc_VER
FILE=$NAME-$glibc_VER$glibc_PRIP

source $SCRIPTS_DIR/include/unpack_sep_bzip

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM
DL=$(readelf -l /bin/sh | sed -n 's@.*interpret.*/tools\(.*\)]$@\1@p')
sed -i "s|libs -o|libs -L/usr/lib -Wl,-dynamic-linker=$DL -o|" \
scripts/test-installation.pl
unset DL

sed -i 's|@BASH@|/bin/bash|' elf/ldd.bash.in

cd $BUILD_DIR/$PROGRAM-BUILD

case `uname -m` in
i?86) echo "CFLAGS += -march=i486 -mtune=native -O3 -pipe" > configparms ;;
esac

	echo -e "$G ../$PROGRAM/configure $DEF" 
    ../$PROGRAM/configure --prefix=/usr \
--disable-profile --enable-add-ons \
--enable-kernel=2.6.18 --libexecdir=/usr/lib/glibc
    if [ $? -ne 0 ]
		then
			echo -e "$R Configure selhalo $DEF"
			exit 1
	fi
    echo -e "$G make $DEF"
    make
    if [ $? -ne 0 ]
		then
			echo -e "$R make selhalo $DEF"
			exit 1
	fi
	
	cp -v ../$PROGRAM/iconvdata/gconv-modules iconvdata

    echo -e "$G make check $DEF"
    make -k check 2>&1 | tee $BUILD_DIR/glibc-check-log
	grep Error glibc-check-log

	echo -e "$R **************************************************** $DEF"
	echo -e "$R **************************************************** $DEF"
	echo -e "$R ************ Pozor zkontrolujte soubor ************* $DEF"
	echo -e "$R ************** $BUILD_DIR/glibc-check-log ************** $DEF" 
	echo -e "$R ************ Informace najdete v README ************ $DEF"
	echo -e "$R ********** !! Nepreskakujte tentok krok !! ********* $DEF"
	echo -e "$R **************************************************** $DEF"
	echo -e "$R **************************************************** $DEF"
	echo -e "$G pokracujte stiskem <ENTER> $DEF"
	read > /dev/null

	echo -e "$C Vytvarim soubor $G touch /etc/ld.so.conf $DEF"
	touch /etc/ld.so.conf
			
    echo -e "$G make-install $DEF"
    make install
    if [ $? -ne 0 ]
		then
			echo -e "$R make install selhalo $DEF"
			exit 1
	fi
	
	echo -e "$C Vytvarim slozku $G mkdir -pv /usr/lib/locale $C pro locale $DEF"
	mkdir -pv /usr/lib/locale
	echo -e "$C Nastavuju locale $DEF"
	localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
	localedef -i en_US -f ISO-8859-1 en_US
	localedef -i en_US -f UTF-8 en_US.UTF-8
	
	echo -e "$C Vytvarim soubor $G /etc/nsswitch.conf $C pro qlibc $DEF"
		cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf
passwd: files
group: files
shadow: files
hosts: files dns
networks: files
protocols: files
services: files
ethers: files
rpc: files
# End /etc/nsswitch.conf
EOF
	
	echo -e "$C Nastaveni timezone $DEF"
	cp -v --remove-destination /usr/share/zoneinfo/CET /etc/localtime
	
	echo -e "$C Vytvarim soubor $G /etc/ld.so.conf $C pro qlibc $DEF"
	cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib
# End /etc/ld.so.conf
EOF
	
	
if [ $BUILD_RM == 1 ];
	then
                echo -e "$C Mazu slozku s buildem $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM-BUILD $DEF"
                rm -rf $BUILD_DIR/$PROGRAM-BUILD
                echo -e "$C Mazu slozku se zdrojaky $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
                rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi
cd $ROOT
