#!/bin/bash

NAME=${glibc[0]}
PROGRAM=${glibc[3]}
FILE=${glibc[2]}
EXT=${glibc[4]}
DLINK=${glibc[1]}
MD5=${glibc[5]}
pDLINK=${pglibc[0]}
pMD5=${pglibc[2]}
pPatch=${pglibc[1]}

download ${DLINK}
download ${pDLINK}

waitUser

check ${FILE} ${MD5}
check ${pPatch} ${pMD5}

waitUser

unpack ${EXT}

waitUser

SepBuild

waitUser

startBuild
cd $BUILD_DIR/$PROGRAM
{
	DL=$(readelf -l /bin/sh | sed -n 's@.*interpret.*/tools\(.*\)]$@\1@p')
	sed -i "s|libs -o|libs -L/usr/lib -Wl,-dynamic-linker=$DL -o|" \
        scripts/test-installation.pl
	unset DL
	waitUser	
	sed -i -e 's/"db1"/& \&\& $name ne "nss_test1"/' scripts/test-installation.pl
	waitUser
	sed -i 's|@BASH@|/bin/bash|' elf/ldd.bash.in
	waitUser
	addPatch ${pPatch}
	waitUser
	sed -i '195,213 s/PRIVATE_FUTEX/FUTEX_CLOCK_REALTIME/' \
nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_timed{rd,wr}lock.S
	waitUser
cd $BUILD_DIR/$NAME-BUILD

case `uname -m` in
  i?86) echo "CFLAGS += -march=i486 -mtune=native -O3 -pipe" > configparms ;;
esac
	echo -e "$G ../$PROGRAM/configure $DEF" 
	../$PROGRAM/configure --prefix=/usr \
    --disable-profile --enable-add-ons \
    --enable-kernel=2.6.22.5 --libexecdir=/usr/lib/glibc || exit 1
	StartMake
	waitUser
	make || exit 1
	waitUser
	cp -v ../glibc-2.13/iconvdata/gconv-modules iconvdata
	waitUser
	echo -e "$G make check $DEF"
	make -k check 2>&1 | tee glibc-check-log
	echo -e "$R Check Errors $DEF"
	grep Error $BUILD_DIR/$NAME-BUILD/glibc-check-log

	echo -e "$R **************************************************** $DEF"
	echo -e "$R Check tect on top for erors and file ${BUILD_DIR}/${PROGRAM}/glibc-check-log $DEF"
	echo -e "$R **************************************************** $DEF"
	echo -e "$G pres <ENTER> for continue $DEF"
	read > /dev/null

	echo -e "$C $L_VAR_MF $G touch /etc/ld.so.conf $DEF"
	touch /etc/ld.so.conf
	StartMakeInstall
	waitUser		
	make install || exit 1
	
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-chap6.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
cd $ROOT
