#!/bin/bash

NAME=${gmp[0]}
PROGRAM=${gmp[3]}
FILE=${gmp[2]}
EXT=${gmp[4]}
DLINK=${gmp[1]}
MD5=${gmp[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	if [ $on64 == 1 ];
	  then
		echo -e "$G $PROGRAM/configure $DEF" 
		ABI=32 ./configure --prefix=/usr --enable-cxx --enable-mpbsd || exit 1
	  else	
		echo -e "$G $PROGRAM/configure $DEF"
		./configure --prefix=/usr --enable-cxx --enable-mpbsd || exit 1
	fi

	c_Make || exit 1
	
	echo -e "$G make check $DEF"
	make check 2>&1 | tee gmp-check-log
	
	awk '/tests passed/{total+=$2} ; END{print total}' gmp-check-log
	waitUserAl
	
	c_MakeInstall || exit 1

	mkdir -v /usr/share/doc/gmp-5.0.1
cp    -v doc/{isa_abi_headache,configuration} doc/*.html \
         /usr/share/doc/gmp-5.0.1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
