#!/bin/bash

NAME=${grep[0]}
PROGRAM=${grep[3]}
FILE=${grep[2]}
EXT=${grep[4]}
DLINK=${grep[1]}
MD5=${grep[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr \
    --bindir=/bin || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
