#!/bin/bash

NAME=${groff[0]}
PROGRAM=${groff[3]}
FILE=${groff[2]}
EXT=${groff[4]}
DLINK=${groff[1]}
MD5=${groff[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	PAGE=A4 ./configure --prefix=/usr || exit 1

	c_Make || exit 1

	c_MakeInstall || exit 1

	ln -sv eqn /usr/bin/geqn
	ln -sv tbl /usr/bin/gtbl

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
