#!/bin/bash

NAME=${grub[0]}
PROGRAM=${grub[3]}
FILE=${grub[2]}
EXT=${grub[4]}
DLINK=${grub[1]}
MD5=${grub[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr           \
             --sysconfdir=/etc       \
             --disable-grub-emu-usb  \
             --disable-grub-fstest   \
             --disable-efiemu || exit 1
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
