#!/bin/bash

NAME=${gzip[0]}
PROGRAM=${gzip[3]}
FILE=${gzip[2]}
EXT=${gzip[4]}
DLINK=${gzip[1]}
MD5=${gzip[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --bindir=/bin || exit 1

	c_Make || exit 1
	
	c_MakeTest check  || exit 1
	
	c_MakeInstall || exit 1

	mv -v /bin/{gzexe,uncompress,zcmp,zdiff,zegrep} /usr/bin
	mv -v /bin/{zfgrep,zforce,zgrep,zless,zmore,znew} /usr/bin
	
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
