#!/bin/bash

NAME=${iproute2[0]}
PROGRAM=${iproute2[3]}
FILE=${iproute2[2]}
EXT=${iproute2[4]}
DLINK=${iproute2[1]}
MD5=${iproute2[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	sed -i '/^TARGETS/s@arpd@@g' misc/Makefile
	sed -i '1289i\\tfilter.cloned = 2;' ip/iproute.c

	make DESTDIR= || exit 1
	
	make DESTDIR= SBINDIR=/sbin MANDIR=/usr/share/man \
     DOCDIR=/usr/share/doc/iproute2-2.6.37 install || exit 1
	
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
