#!/bin/bash

NAME=${linux[0]}
PROGRAM=${linux[3]}
FILE=${linux[2]}
EXT=${linux[4]}
DLINK=${linux[1]}
MD5=${linux[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

{
cd $BUILD_DIR/$PROGRAM
	echo -e "$G make mrproper $DEF" 
	make mrproper || exit 1
  
	waitUser

	echo -e "$G make headers_check $DEF"
	make headers_check || exit 1

	waitUser

	echo -e "$G make INSTALL_HDR_PATH=dest headers_install $DEF"
	make INSTALL_HDR_PATH=dest headers_install || exit 1

	waitUser

	echo -e "$G find dest/include \( -name .install -o -name ..install.cmd \) -delete $DEF" 
	find dest/include \( -name .install -o -name ..install.cmd \) -delete

	waitUser

	copyFilesRec dest/include/* /usr/include

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-ch6.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$R build selhal $DEF"
		exit 1
fi  

waitUser
RMsource
cd $ROOT
