#!/bin/bash

NAME=linux
PROGRAM=$NAME-$linux_VER
FILE=$NAME-$linux_VER$linux_PRIP

echo -e "$Y Spoustim build script programu $PROGRAM $DEF"

source $SCRIPTS_DIR/include/unpack_bzip

echo -e "$Y Spoustim Build $DEF"

cd $BUILD_DIR/$PROGRAM
	echo -e "$G make mrproper $DEF" 
    make mrproper

    echo -e "$G make headers_check $DEF"
    make headers_check
    if [ $? -ne 0 ]
		then
			echo -e "$R make headers_check selhalo $DEF"
			exit 1
	fi
    echo -e "$G make INSTALL_HDR_PATH=dest headers_install $DEF"
    make INSTALL_HDR_PATH=dest headers_install
	if [ $? -ne 0 ]
		then
			echo -e "$R mmake INSTALL_HDR_PATH=dest headers_install selhalo $DEF"
			exit 1
	fi
	echo -e "$C mazu nepotrebne soubory $DEF" 
	echo -e "$G find dest/include \( -name .install -o -name ..install.cmd \) -delete $DEF" 
	find dest/include \( -name .install -o -name ..install.cmd \) -delete
	echo -e "$C kopiruji potrebne soubory $DEF" 
	echo -e "$G cp -rv dest/include/* /usr/include $DEF" 
	cp -rv dest/include/* /usr/include
	
if [ $BUILD_RM == 1 ];
	then
                echo -e "$C Mazu slozku se zdrojaky $DEF"
                echo -e "$G rm -rf $BUILD_DIR/$PROGRAM $DEF"
                rm -rf $BUILD_DIR/$PROGRAM
	else
		echo -e "$C Slozka s buildem a zdrojaky ponechana $DEF"
fi
cd $ROOT
