#!/bin/bash

NAME=${manpage[0]}
PROGRAM=${manpage[3]}
FILE=${manpage[2]}
EXT=${manpage[4]}
DLINK=${manpage[1]}
MD5=${manpage[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

{
cd $BUILD_DIR/$PROGRAM

    c_MakeInstall

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM-ch6.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$R build selhal $DEF"
		exit 1
fi  
waitUser
RMsource
cd $ROOT
