#!/bin/bash

NAME=${mandb[0]}
PROGRAM=${mandb[3]}
FILE=${mandb[2]}
EXT=${mandb[4]}
DLINK=${mandb[1]}
MD5=${mandb[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{


	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --libexecdir=/usr/lib \
    --docdir=/usr/share/doc/man-db-2.5.9 --sysconfdir=/etc --disable-setuid \
    --with-browser=/usr/bin/lynx --with-vgrind=/usr/bin/vgrind \
    --with-grap=/usr/bin/grap || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest -k check || exit 1
	StartMakeInstall
	waitUser
	c_MakeInstall || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
