#!/bin/bash

NAME=${mpfr[0]}
PROGRAM=${mpfr[3]}
FILE=${mpfr[2]}
EXT=${mpfr[4]}
DLINK=${mpfr[1]}
MD5=${mpfr[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{

	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --enable-thread-safe --docdir=/usr/share/doc/mpfr-3.0.0 || exit 1

	c_Make || exit 1
	
	echo -e "$G make check $DEF"
	make check || exit 1
		
	c_MakeInstall || exit 1

	echo -e "$G make html $DEF" 
	make html || exit 1

	echo -e "$G make install-html $DEF" 
	make install-html || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
