#!/bin/bash

NAME=${patch[0]}
PROGRAM=${patch[3]}
FILE=${patch[2]}
EXT=${patch[4]}
DLINK=${patch[1]}
MD5=${patch[5]}
pFILE=${ppatch[1]}
pDLINK=${ppatch[0]}
pMD5=${ppatch[2]}

download ${DLINK}
download ${pDLINK}

waitUser

check ${FILE} ${MD5}
check ${pFILE} ${pMD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	addPatch ${FILE}

	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr || exit 1

	c_Make || exit 1
	
	c_MakeTest check || exit 1
	
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
