#!/bin/bash

NAME=${pkgconfig[0]}
PROGRAM=${pkgconfig[3]}
FILE=${pkgconfig[2]}
EXT=${pkgconfig[4]}
DLINK=${pkgconfig[1]}
MD5=${pkgconfig[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
sed -i -e 's/XT])dnl/XT])[]dnl/' \
       -e 's/\.])dnl/\.])[]dnl/' pkg.m4

	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr || exit 1
	
	c_Make || exit 1
	 
	c_MakeTest check || exit 1

	c_MakeInstall || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
