#!/bin/bash

NAME=${procps[0]}
PROGRAM=${procps[3]}
FILE=${procps[2]}
EXT=${procps[4]}
DLINK=${procps[1]}
MD5=${procps[5]}
pFILE=${pprocps[1]}
pDLINK=${pprocps[0]}
pMD5=${pprocps[2]}
p2FILE=${pprocps2[1]}
p2DLINK=${pprocps2[0]}
p2MD5=${pprocps2[2]}

download ${DLINK}
download ${pDLINK}
download ${p2DLINK}

waitUser

check ${FILE} ${MD5}
check ${pFILE} ${pMD5}
check ${p2FILE} ${p2MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	addPatch ${pFILE}
	addPatch ${p2FILE}
	waitUser
	sed -i -e 's@\*/module.mk@proc/module.mk ps/module.mk@' Makefile
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
