#!/bin/bash

NAME=${psmisc[0]}
PROGRAM=${psmisc[3]}
FILE=${psmisc[2]}
EXT=${psmisc[4]}
DLINK=${psmisc[1]}
MD5=${psmisc[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	sed -i 's@#include <sys\/user.h>@#include <bits\/types.h>\n&@' configure
	waitUser
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr || exit 1
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	mv -v /usr/bin/fuser /bin
	mv -v /usr/bin/killall /bin
	waitUser
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
