#!/bin/bash

NAME=${shadow[0]}
PROGRAM=${shadow[3]}
FILE=${shadow[2]}
EXT=${shadow[4]}
DLINK=${shadow[1]}
MD5=${shadow[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;
sed -i 's/man_MANS = $(man_nopam) /man_MANS = /' man/ru/Makefile.in
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs
waitUser
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --sysconfdir=/etc || exit 1
	StartMake
	waitUser
	make || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	mv -v /usr/bin/passwd /bin
	waitUser
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	  


pwconv

grpconv

sed -i 's/yes/no/' /etc/default/useradd

echo -e "$R Open other terminal, chroot in to LFS (use scripts/only_chroot) and set root password. $G passwd root $DEF"
echo -e "Than pres enter for continue"
read > /dev/null
RMbuild
cd $ROOT
