#!/bin/bash

NAME=${shadow[0]}
PROGRAM=${shadow[3]}
FILE=${shadow[2]}
EXT=${shadow[4]}
DLINK=${shadow[1]}
MD5=${shadow[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;
	sed -i 's/man_MANS = $(man_nopam) /man_MANS = /' man/ru/Makefile.in
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --sysconfdir=/etc || exit 1

	c_Make || exit 1
	
	c_MakeInstall || exit 1

	mv -v /usr/bin/passwd /bin

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi  	  


pwconv

grpconv

sed -i 's/yes/no/' /etc/default/useradd

echo -e " Open other terminal, chroot in to LFS and set root password. 'passwd root' "

waitUser
RMbuild
cd $ROOT
