#!/bin/bash
DEF="$(tput sgr0)"
BOLD="$(tput bold)"
B="${BOLD}$(tput setaf 4)"
G="${BOLD}$(tput setaf 2)"
R="${BOLD}$(tput setaf 1)"
Y="${BOLD}$(tput setaf 3)"
C="${BOLD}$(tput setaf 6)"
M="${BOLD}$(tput setaf 5)"
ROOT=/mnt/LFS	#složka připojeného obrazu
LFS=$ROOT
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/tools/bin:/bin:/usr/bin
MAKEFLAGS='-j 3' #number of procesor cores


echo -e "$Y Preparing system for chapter 6 $DEF"

#su root

echo -e "$C Making system folders $DEF"
echo -e "$G mkdir -v $LFS/{dev,proc,sys} $DEF"
mkdir -v $LFS/{dev,proc,sys}

echo -e "$C Creating device nodes $DEF"
echo -e "$G mknod -m 600 $LFS/dev/console c 5 1 $DEF"
echo -e "$G mknod -m 666 $LFS/dev/null c 1 3 $DEF"
mknod -m 600 $LFS/dev/console c 5 1
mknod -m 666 $LFS/dev/null c 1 3

echo -e "$C Mounting $G /dev $DEF"
echo -e "$G mount -v --bind /dev $LFS/dev $DEF"
mount -v --bind /dev $LFS/dev

echo -e "$C Mounting VFS $DEF"
echo -e "$G mount -vt devpts devpts $LFS/dev/pts $DEF"
mount -vt devpts devpts $LFS/dev/pts
echo -e "$G mount -vt tmpfs shm $LFS/dev/shm $DEF"
mount -vt tmpfs shm $LFS/dev/shm
echo -e "$G mount -vt proc proc $LFS/proc $DEF"
mount -vt proc proc $LFS/proc
echo -e "$G mount -vt sysfs sysfs $LFS/sys $DEF"
mount -vt sysfs sysfs $LFS/sys

echo -e "$C starting chroot $DEF"
echo -e "$C In chroot run $G /scripts/chroot_makeall $DEF"
chroot "$LFS" /tools/bin/env -i \
HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin SCRIPTS_DIR=/scripts \
/tools/bin/bash --login +h
