#!/bin/bash

NAME=${sysklogd[0]}
PROGRAM=${sysklogd[3]}
FILE=${sysklogd[2]}
EXT=${sysklogd[4]}
DLINK=${sysklogd[1]}
MD5=${sysklogd[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

startBuild

cd $BUILD_DIR/$PROGRAM
{
	StartMake
	waitUser
	make || exit 1
	
	StartMake BINDIR=/sbin install
	waitUser
	make BINDIR=/sbin install || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
if [ $PIPESTATUS -ne 0 ]
	then
		echo -e "$L_FAIL_BUIL"
		exit 1
fi
echo -e "$C making file $G /etc/syslog.conf $DEF"  	  
waitUser
cat > /etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# End /etc/syslog.conf
EOF

RMbuild
cd $ROOT
