#!/bin/bash

NAME=${tar[0]}
PROGRAM=${tar[3]}
FILE=${tar[2]}
EXT=${tar[4]}
DLINK=${tar[1]}
MD5=${tar[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{

	FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr \
    --bindir=/bin --libexecdir=/usr/sbin || exit 1

	c_Make || exit 1

	c_MakeTest check || exit 1
	
	c_MakeInstall || exit 1

	make -C doc install-html docdir=/usr/share/doc/tar-1.25 || exit 1

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
