#!/bin/bash

#
# TODO
#

NAME=${udev[0]}
PROGRAM=${udev[3]}
FILE=${udev[2]}
EXT=${udev[4]}
DLINK=${udev[1]}
MD5=${udev[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
FILEct=${udevct[2]}
FILEtt=${udevtt[2]}
	tar -xvf $SOURCES_DIR/$FILEct
	waitUser
	tar -xvf $SOURCES_DIR/$FILEtt --strip-components=1
	waitUser
	install -dv /lib/{firmware,udev/devices/{pts,shm}}
	mknod -m0666 /lib/udev/devices/null c 1 3
	waitUser
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr \
    --sysconfdir=/etc --sbindir=/sbin \
    --with-rootlibdir=/lib --libexecdir=/lib/udev \
    --disable-extras --disable-introspection || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest check || exit 1
	waitUser
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	rmdir -v /usr/share/doc/udev
	cd udev-config-20100128
	StartMakeInstall
	waitUser
	make install || exit 1
	StartMakeInstall -doc
	waitUser
	make install-doc
  
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
