#!/bin/bash

NAME=${utillinux[0]}
PROGRAM=${utillinux[3]}
FILE=${utillinux[2]}
EXT=${utillinux[4]}
DLINK=${utillinux[1]}
MD5=${utillinux[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


sed -e 's@etc/adjtime@var/lib/hwclock/adjtime@g' \
    -i $(grep -rl '/etc/adjtime' .)
mkdir -pv /var/lib/hwclock

cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --enable-arch --enable-partx --enable-write || exit 1
	
	c_Make

	c_MakeInstall

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
