#!/bin/bash

NAME=${vim[0]}
PROGRAM=${vim[3]}
FILE=${vim[2]}
EXT=${vim[4]}
DLINK=${vim[1]}
MD5=${vim[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --enable-multibyte || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest test || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	ln -sv vim /usr/bin/vi
	for L in  /usr/share/man/{,*/}man1/vim.1; do
	    ln -sv vim.1 $(dirname $L)/vi.1
	done
	waitUser
	ln -sv ../vim/vim73/doc /usr/share/doc/vim-7.3

} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	    
waitUser
cat > /etc/vimrc << "EOF"
" Begin /etc/vimrc

set nocompatible
set backspace=2
syntax on
if (&term == "iterm") || (&term == "putty")
  set background=dark
endif

" End /etc/vimrc
EOF

waitUser
RMbuild
cd $ROOT
