#!/bin/bash

NAME=${xzutils[0]}
PROGRAM=${xzutils[3]}
FILE=${xzutils[2]}
EXT=${xzutils[4]}
DLINK=${xzutils[1]}
MD5=${xzutils[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild


cd $BUILD_DIR/$PROGRAM
{
	echo -e "$G $PROGRAM/configure $DEF" 
	./configure --prefix=/usr --docdir=/usr/share/doc/xz-5.0.1 || exit 1

	c_Make || exit 1
	
	c_MakeTest check || exit 1
	
	c_MakeInstall || exit 1
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
