#!/bin/bash

NAME=${zlib[0]}
PROGRAM=${zlib[3]}
FILE=${zlib[2]}
EXT=${zlib[4]}
DLINK=${zlib[1]}
MD5=${zlib[5]}

download ${DLINK}

waitUser

check ${FILE} ${MD5}

waitUser

unpack ${EXT}

waitUser

startBuild

cd $BUILD_DIR/$PROGRAM
{
	echo -e "$L_FX_HF"
	echo -e "$G sed -i 's/ifdef _LARGEFILE64_SOURCE/ifndef _LARGEFILE64_SOURCE/' zlib.h $DEF"
	sed -i 's/ifdef _LARGEFILE64_SOURCE/ifndef _LARGEFILE64_SOURCE/' zlib.h
	waitUser
	CFLAGS='-mstackrealign -fPIC -O3' ./configure --prefix=/usr || exit 1
	StartMake
	waitUser
	make || exit 1
	
	c_MakeTest check || exit 1
	StartMakeInstall
	waitUser
	make install || exit 1
	waitUser
	echo -e "$L_MV_FIL"
	echo -e "$G mv -v /usr/lib/libz.so.* /lib $DEF"
	mv -v /usr/lib/libz.so.* /lib
	waitUser
	echo -e "$L_MK_LNS"
	echo -e "$G ln -sfv ../../lib/libz.so.1.2.5 /usr/lib/libz.so $DEF"
	ln -sfv ../../lib/libz.so.1.2.5 /usr/lib/libz.so
} 2>&1 | tee $BUILD_DIR/LOG_$PROGRAM.log
	if [ $PIPESTATUS -ne 0 ]
		then
			echo -e "$L_FAIL_BUIL"
			exit 1
	fi  	  
waitUser
RMbuild
cd $ROOT
